### PR TITLE
Added ^ to react and react-dom versions

### PR DESCRIPTION
**Pull request by toxicgorilla**
HI JAKE

AAAALOOOOLOLOLOLOLOLLLOOOOOOOOOOOOL

STEVE IS AWESOME

🍺

### CODE REVIEW

**Comment by RShergold** [comment]
Please add unit tests for each possible version of react and react-dom

**Comment by toxicgorilla** [comment]
WAT

**Comment by toxicgorilla** [comment]
no

**Comment by RShergold** [comment]
Please ensure all contractors (irregardless of payment method) give vendor read AND write access to:
the source repository
all testing and build servers
at least one fake tinder profile

**Comment by JakeSidSmith** [comment]
Hi, Phteven (@toxicgorilla), thanks for your interest in my library.

There are some more changes that need to be made to the dependencies, so I will close this PR and get another one sorted asap.

**Pull request closed without merging**
