### PR TITLE
Added: areaColor prop for color overriding or gradients

### PR DESCRIPTION
**Pull request by jackall3n**
There are use cases where you might want the areaColor to be different to the stroke color. It would be nice for this to also be able to be a gradient. 

I've add a really simple top to bottom gradient using an areaColor array of strings.

### CODE REVIEW

**Comment by jackall3n** [comment]
@JakeSidSmith what's your thought on this PR?

**Comment by JakeSidSmith** [comment]
I'm happy to accept this, just haven't had a chance to look in the past week as I've been away. Will try to get a new version published today. 🙂

Is this totally backward compatible?

**Comment by JakeSidSmith** [comment]
Closed and re-opened to kick off CI (was previously set to not run for forks).

**Comment by JakeSidSmith** [comment]
Just noticed, I know it's not explicit in my linting rules, but there is now a mixture of 2 and 4 space indentation. Could you fix this please (2 space all over)? 😊

**Comment by jackall3n** [comment]
Totally backwardly compatible. I've updated the examples to include a graph with this gradient. All previously generated graphs work as expected. 

I've fixed the spacing issue you've mentioned, also. :)

**Comment by JakeSidSmith** [comment]
Now published as `1.0.1`, @jackall3n . 😊

**Comment by jackall3n** [comment]
Awesome, thanks for pushing that 😊

**Pull request merged**
